### ISSUE TITLE
Add builds for web components 

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#240]
Should be easier to use with shadow dom

**Comment by NielsJorck** [comment]
The main issue I get when using web components is the reliance on `:where(html)` in the styling since the web component doesn't have the html element.

In my current project I've made a local copy of `open-props.min.css` and `normalize.min.css` simply appending the host selector eg. `:where(html), :host`

So far it is working fine.

There is also the build scripts currently example `gen:nowhere`.
Not exactly sure how it works or how to use it, haven't had the pleasure to use it yet 😅

Code from `props.js`
```js
const [,,prefix='',useWhere] = process.argv

const selector = useWhere === 'true' ? ':where(html)' : 'html'
```

Could possibly have another build swapping out `:where(html)` for `:host` fairly easily without interrupting the regular usage?
If just adding `:host` by default isn't wanted. Not sure if it would have any side effects 🤔

**Comment by backlineint** [comment]
Excited to see this feature land. Used an approach similar to what @NielsJorck described to work around it, which should no longer be necessary.
