### ISSUE TITLE
Button border changes linger for 3 seconds

### ISSUE THREAD

**Issue by fractaledmind** [argyleink/open-props#250]
I am trying to figure out if there is some use case I am missing, but to my experience it feels like a bug to have button border transitions linger on the transition out for 3 seconds.

This is due to CSS like:
```css
transition: border-color .5s var(--ease-3) 3s;
```

However, this is an excellent library and a joy to use, so thank you!

**Comment by argyleink** [comment]
yes, i agree it's a bit non-standard to have a lingering effect that your focus/mouse was there, but I also thought it was kinda cool and unique. 

if you dont like it, it's super easy to change tho! helps the lib uses `:where(button)` so you dont have to fight it

```css
button {
  transition-delay: 0;
}
```

glad it's otherwise been enjoyable for you! 🙂

**Comment by fractaledmind** [comment]
I see. "Cool and unique" is reason enough for me. And indeed, I have overridden it myself. I just wasn't sure if it was intentional or not. 

And yes, it is a great (and beautiful) project.
