### ISSUE TITLE
Normalize adds a stroke to some inline SVGs that seems unintended

### ISSUE THREAD

**Issue by ezzatron** [argyleink/open-props#312]
Hey, loving open props so far ❤️

I noticed something weird when using normalize with inline SVGs - some paths get a stroke applied to them that seems like a bug. Here's an example using a Mapbox GL JS map with a marker:

https://user-images.githubusercontent.com/100152/200550523-d39a8672-fd11-482d-b9b1-4a82645df870.mov

The issue seems to come from this line in normalize: https://github.com/argyleink/open-props/blob/07fbde3d9f1eab7f8cb6d1791b2c8aabb9a578b6/src/extra/normalize.src.css#L148

I'm sure there's some sound logic behind that rule, but right now I'm having trouble figuring out what its purpose is.

**Comment by argyleink** [comment]
the idea was that if an svg wasnt filled, it'll otherwise be invisible, so the normalize css code turns the svg into an outlined svg instead of a filled one. so far you're the first to notice it in an undesirable way, my guess is that the svg element itself has not `fill` attribute but the children do?

i just played with an update.. which would mitigate this, but isn't a final solution I dont think. 

```css
:where(svg):where(:not([fill])):not(:has([fill])) {
  ...
}
```

this makes it a little bit smarter at the cost of not working at all in browsers without `:has()`, but it now is looking to see if any children are filled before giving the svg a stroke. 

maybe this is trying to be too convenient?

on the other hand, it's very easy to fix with some custom author side code:

```css
svg:not([fill]) {
  stroke: unset;
  fill: unset;
}
```

**Comment by ezzatron** [comment]
> my guess is that the svg element itself has not `fill` attribute but the children do?

Yeah, that seems to be the case. I noticed it in two separate places on the same page I was trying to convert to use Open Props. One was Mapbox (as above), the other was an in-house SVG logo (which just got a bit "chonkier"). Neither has a `fill` attribute on the `svg` element, but they do have `fill` on sub-elements. I'm guessing that updated rule (using `:has`) would probably fix the issue, unless the SVG had its `fill` set via external CSS.

I don't really feel like I know the landscape well enough to comment on the convenience factor. All I know is, it kind of violated the "principle of least surprise" a bit for me. I didn't expect using `normalize` to alter the appearance of my SVGs.

In any case, I can confirm that the suggested workaround fixes the issues I'm seeing 🙏

**Comment by argyleink** [comment]
yeah, Open Props itself has 0 surprises, but `normalize.css` files are opinionated by definition.

one of the benefits of this Open Props normalize is that it's no battle to override and customize, making any issues it's causing easy to fix, which it sounds like you've already implemented and moved on 🙂 

i'll give that `:has()` addition some more thought, seems reasonable to add it because it can add chunk to an svg if fills are on children.
