### ISSUE TITLE
Wrong usage with --safariONLY media.

### ISSUE THREAD

**Issue by equinusocio** [argyleink/open-props#85]
The doc show that `--safariONLY` is used as `@media`, but [checking the code](https://github.com/argyleink/open-props/blob/main/src/props.supports.css), it uses a property-check. So this:

![Screenshot 2021-12-02 at 14 45 43](https://user-images.githubusercontent.com/10454741/144433934-ba9eee40-c79e-4e57-ad9f-61696b2cd62e.png)

should be:

```css
@supports (--safariONLY) {
 ...
}
```

and not a `@media` at-rule

**Comment by argyleink** [comment]
nice catch, yeah, the @custom-media plugin doesnt support @custom-supports (turns out there's no spec for this yet, i've asked). i should pull the example because the only way to get it to work is to use the --safariONLY in an @supports like you say, which postcss can't do.

maybe i'll pull it and put it in a back pocket for use later. definitely a bit misleading, even tho they do work as @supports, they're pitched as custom media.
